/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imasjava_wrapper_LowLevel */

#ifndef _Included_imasjava_wrapper_LowLevel
#define _Included_imasjava_wrapper_LowLevel
#ifdef __cplusplus
extern "C" {
#endif
#undef imasjava_wrapper_LowLevel_MAXDIM
#define imasjava_wrapper_LowLevel_MAXDIM 7L
#undef imasjava_wrapper_LowLevel_OP_INTERP_0
#define imasjava_wrapper_LowLevel_OP_INTERP_0 0L
#undef imasjava_wrapper_LowLevel_BACKEND_ID_0
#define imasjava_wrapper_LowLevel_BACKEND_ID_0 10L
#undef imasjava_wrapper_LowLevel_OP_RANGE_0
#define imasjava_wrapper_LowLevel_OP_RANGE_0 20L
#undef imasjava_wrapper_LowLevel_OP_ACCESS_0
#define imasjava_wrapper_LowLevel_OP_ACCESS_0 30L
#undef imasjava_wrapper_LowLevel_ACCESS_PULSE_0
#define imasjava_wrapper_LowLevel_ACCESS_PULSE_0 40L
#undef imasjava_wrapper_LowLevel_DATA_TYPE_0
#define imasjava_wrapper_LowLevel_DATA_TYPE_0 50L
#undef imasjava_wrapper_LowLevel_ERR_0
#define imasjava_wrapper_LowLevel_ERR_0 -1L
#undef imasjava_wrapper_LowLevel_TIMED
#define imasjava_wrapper_LowLevel_TIMED 1L
#undef imasjava_wrapper_LowLevel_NON_TIMED
#define imasjava_wrapper_LowLevel_NON_TIMED 0L
#undef imasjava_wrapper_LowLevel_GLOBAL_OP
#define imasjava_wrapper_LowLevel_GLOBAL_OP 20L
#undef imasjava_wrapper_LowLevel_SLICE_OP
#define imasjava_wrapper_LowLevel_SLICE_OP 21L
#undef imasjava_wrapper_LowLevel_READ_OP
#define imasjava_wrapper_LowLevel_READ_OP 30L
#undef imasjava_wrapper_LowLevel_WRITE_OP
#define imasjava_wrapper_LowLevel_WRITE_OP 31L
#undef imasjava_wrapper_LowLevel_REPLACE_OP
#define imasjava_wrapper_LowLevel_REPLACE_OP 32L
#undef imasjava_wrapper_LowLevel_UNDEFINED_INTERP
#define imasjava_wrapper_LowLevel_UNDEFINED_INTERP 0L
#undef imasjava_wrapper_LowLevel_CLOSEST_INTERP
#define imasjava_wrapper_LowLevel_CLOSEST_INTERP 1L
#undef imasjava_wrapper_LowLevel_PREVIOUS_INTERP
#define imasjava_wrapper_LowLevel_PREVIOUS_INTERP 2L
#undef imasjava_wrapper_LowLevel_LINEAR_INTERP
#define imasjava_wrapper_LowLevel_LINEAR_INTERP 3L
#undef imasjava_wrapper_LowLevel_UNDEFINED_TIME
#define imasjava_wrapper_LowLevel_UNDEFINED_TIME -999L
#undef imasjava_wrapper_LowLevel_OPEN_PULSE
#define imasjava_wrapper_LowLevel_OPEN_PULSE 40L
#undef imasjava_wrapper_LowLevel_FORCE_OPEN_PULSE
#define imasjava_wrapper_LowLevel_FORCE_OPEN_PULSE 41L
#undef imasjava_wrapper_LowLevel_CREATE_PULSE
#define imasjava_wrapper_LowLevel_CREATE_PULSE 42L
#undef imasjava_wrapper_LowLevel_FORCE_CREATE_PULSE
#define imasjava_wrapper_LowLevel_FORCE_CREATE_PULSE 43L
#undef imasjava_wrapper_LowLevel_CLOSE_PULSE
#define imasjava_wrapper_LowLevel_CLOSE_PULSE 44L
#undef imasjava_wrapper_LowLevel_ERASE_PULSE
#define imasjava_wrapper_LowLevel_ERASE_PULSE 45L
#undef imasjava_wrapper_LowLevel_CHAR_DATA
#define imasjava_wrapper_LowLevel_CHAR_DATA 50L
#undef imasjava_wrapper_LowLevel_INTEGER_DATA
#define imasjava_wrapper_LowLevel_INTEGER_DATA 51L
#undef imasjava_wrapper_LowLevel_DOUBLE_DATA
#define imasjava_wrapper_LowLevel_DOUBLE_DATA 52L
#undef imasjava_wrapper_LowLevel_COMPLEX_DATA
#define imasjava_wrapper_LowLevel_COMPLEX_DATA 53L
#undef imasjava_wrapper_LowLevel_UNKNOWN_ERR
#define imasjava_wrapper_LowLevel_UNKNOWN_ERR -1L
#undef imasjava_wrapper_LowLevel_CONTEXT_ERR
#define imasjava_wrapper_LowLevel_CONTEXT_ERR -2L
#undef imasjava_wrapper_LowLevel_BACKEND_ERR
#define imasjava_wrapper_LowLevel_BACKEND_ERR -3L
#undef imasjava_wrapper_LowLevel_LOWLEVEL_ERR
#define imasjava_wrapper_LowLevel_LOWLEVEL_ERR -4L
#undef imasjava_wrapper_LowLevel_NODATA_ERR
#define imasjava_wrapper_LowLevel_NODATA_ERR -5L
#undef imasjava_wrapper_LowLevel_NO_BACKEND
#define imasjava_wrapper_LowLevel_NO_BACKEND 10L
#undef imasjava_wrapper_LowLevel_ASCII_BACKEND
#define imasjava_wrapper_LowLevel_ASCII_BACKEND 11L
#undef imasjava_wrapper_LowLevel_MDSPLUS_BACKEND
#define imasjava_wrapper_LowLevel_MDSPLUS_BACKEND 12L
#undef imasjava_wrapper_LowLevel_HDF5_BACKEND
#define imasjava_wrapper_LowLevel_HDF5_BACKEND 13L
#undef imasjava_wrapper_LowLevel_MEMORY_BACKEND
#define imasjava_wrapper_LowLevel_MEMORY_BACKEND 14L
#undef imasjava_wrapper_LowLevel_UDA_BACKEND
#define imasjava_wrapper_LowLevel_UDA_BACKEND 15L
/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_print_context
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1print_1context
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_pulse_action
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1pulse_1action
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_open_pulse
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1open_1pulse
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_close_pulse
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1close_1pulse
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_global_action
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1global_1action
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_slice_action
 * Signature: (ILjava/lang/String;IDI)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1slice_1action
  (JNIEnv *, jclass, jint, jstring, jint, jdouble, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_end_action
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1end_1action
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_write_data_int
 * Signature: (ILjava/lang/String;Ljava/lang/String;[III[I)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1write_1data_1int
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_write_data_double
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DII[I)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1write_1data_1double
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_write_data_char
 * Signature: (ILjava/lang/String;Ljava/lang/String;[BII[I)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1write_1data_1char
  (JNIEnv *, jclass, jint, jstring, jstring, jbyteArray, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_read_data_int
 * Signature: (ILjava/lang/String;Ljava/lang/String;II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_imasjava_wrapper_LowLevel_ual_1read_1data_1int
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_read_data_double
 * Signature: (ILjava/lang/String;Ljava/lang/String;II[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_imasjava_wrapper_LowLevel_ual_1read_1data_1double
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_read_data_char
 * Signature: (ILjava/lang/String;Ljava/lang/String;II[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_imasjava_wrapper_LowLevel_ual_1read_1data_1char
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_delete_data
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1delete_1data
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_arraystruct_action
 * Signature: (ILjava/lang/String;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1arraystruct_1action
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_iterate_over_arraystruct
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imasjava_wrapper_LowLevel_ual_1iterate_1over_1arraystruct
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
